### ISSUE TITLE
Example Create a KNX link default/and more options

### ISSUE THREAD

**Issue by rafaelkan** [calimero-project/introduction#1]
In the first class, not exist method: **new KNXNetworkLinkIP(remoteHost, TPSettings.TP1);**

And the second class, TUNNELING is not visible: **KNXNetworkLinkIP.TUNNELING**

Can solved?

**Comment by calimero-project** [comment]
Use the examples in the folder `src/main` which are written for Calimero version 2.4 (that's the version you are using). There is a dedicated section of examples in the README. The example you tried is for Calimero versions < 2.4.

**Comment by rafaelkan** [comment]
Thanks
