### ISSUE TITLE
How to use USB Gateway in samples with working USB device in calimero-server

### ISSUE THREAD

**Issue by olterion** [calimero-project/introduction#11]
Hello,

i want to use the samples CreateUsbLink and DiscoverUsbDevices with my USB KNX Gateway.
In calimero-server it is found as following device:
```
[knx-server] INFO calimero.usb - Found 1 KNX USB devices:
 |--Bus 002 Device 020: ID 135e:0022
[knx-server] INFO calimero.usb.135e:0022 - Bus 002 Device 020: ID 135e:0022
```

But in the sample DiscoverUsbDevices the error is shown:
```
List of KNX USB devices:
none found
```

And in the CreateUsbLink example this error is displayed:
`Error creating USB network link: io.calimero.KNXException: no service provider available for io.calimero.serial.usb.spi.UsbConnectionProvider`

How can I find my UBS uinterface with this examples?

I use windows and start the examples with `gradlew run -DmainClass=DiscoverUsbDevices` and `gradlew run -DmainClass=CreateUsbLink `

Thanks!

**Comment by bmalinowsky** [comment]
The dependency on the usb provider was not listed in gradle. It should work now.

**Comment by olterion** [comment]
Hello,

with your adjustment it works perfectly now!
Thanks!

**Comment by bmalinowsky** [comment]
Thanks for reporting!
