### ISSUE TITLE
KNXNetworkLinkIP visibility:: PushButtonActuator.java 

### ISSUE THREAD

**Issue by lewie** [calimero-project/introduction#3]
Since KNXNetworkLinkIP visibility is protected, this is not working:
See introduction/examples/java8/PushButtonActuator.java Line 144:
```try (final KNXNetworkLink link = new KNXNetworkLinkIP(null, null, new KnxIPSettings(deviceAddress));) {```

How should I rewrite this best practice?

Thanks
Helmut

**Comment by calimero-project** [comment]
Both the class and the used constructor are public ([line 195 here](https://github.com/calimero-project/calimero-core/blob/v2.3/src/tuwien/auto/calimero/link/KNXNetworkLinkIP.java)):

```
public KNXNetworkLinkIP(NetworkInterface, InetAddress, KNXMediumSettings)
```

Do you mean to rewrite the call to use `protected KNXNetworkLinkIP(int, KNXnetIPConnection, KNXMediumSettings)`?

**Comment by lewie** [comment]
Ahh, sorry, I referred to the branch master.

In master, there [*KNXNetworkLinkIP*](https://github.com/calimero-project/calimero-core/blob/master/src/tuwien/auto/calimero/link/KNXNetworkLinkIP.java#L181) functions are protected. Instead, there are two new functions to realize  this: [*newRoutingLink*](https://github.com/calimero-project/calimero-core/blob/master/src/tuwien/auto/calimero/link/KNXNetworkLinkIP.java#L147), [*newTunnelingLink*](https://github.com/calimero-project/calimero-core/blob/master/src/tuwien/auto/calimero/link/KNXNetworkLinkIP.java#L112).

Now more precisely: How should I rewrite *PushButtonActuator* with current *KNXNetworkLinkIP Class* in branch master?

**Comment by calimero-project** [comment]
The same example already exists for the master branch [here](https://github.com/calimero-project/introduction/blob/master/src/main/java/PushButtonDevice.java).

Basically its `KNXNetworkLinkIP.newRoutingLink((NetworkInterface) null, null,
				new KnxIPSettings(deviceAddress))` for an all-defaults knx ip link

**Comment by lewie** [comment]
Oh no! Sorry for wasting your Time!!
