### ISSUE TITLE
原始帧解析组地址和数据类型的方法是哪个？

### ISSUE THREAD

**Issue by pengzhenkun** [calimero-project/introduction#5]
原始帧解析组地址和数据类型的方法是哪个？

**Comment by calimero-project** [comment]
A group address is transmitted with L-Data frames and can be queried using [CEMILData::getDestination](https://github.com/calimero-project/calimero-core/blob/7e6f547c6bd75fa985bfeb5b47ba671df2ea01e8/src/tuwien/auto/calimero/cemi/CEMILData.java#L316)

The data type is implicitly known and not transmitted, you can use, e.g., [ofBitSize](https://github.com/calimero-project/calimero-core/blob/7e6f547c6bd75fa985bfeb5b47ba671df2ea01e8/src/tuwien/auto/calimero/dptxlator/TranslatorTypes.java#L505) with the bit length of a received ASDU to get a list of all supported data types of that specific length.
