### ISSUE TITLE
Error creating KNXnet/IP tunneling link: tuwien.auto.calimero.KNXTimeoutException: timeout connecting to control endpoint /192.168.10.13:3671

### ISSUE THREAD

**Issue by AlexMun86** [calimero-project/introduction#7]
Hi, I've tried to run this in gradle. But getting this error message. Any suggestions?

`Establish a tunneling connection to the KNXnet/IP server /192.168.10.13:3671
19:22:15:555 TRACE Net - match local address /127.0.0.1/8 to /192.168.10.13
19:22:15:555 TRACE Net - match local address /192.168.62.198/24 to /192.168.10.13
19:22:15:555 DEBUG calimero.knxnetip.KNXnet/IP Tunneling 192.168.10.13:3671 - establish connection from 192.168.62.198:59189 to 192.168.10.13:3671 (udp)
19:22:15:555 DEBUG calimero.knxnetip.KNXnet/IP Tunneling 192.168.10.13:3671 - wait for connect response from 192.168.10.13:3671 ...
19:22:25:586 ERROR calimero.knxnetip.KNXnet/IP Tunneling 192.168.10.13:3671 - establishing connection failed, timeout connecting to control endpoint /192.168.10.13:3671
Error creating KNXnet/IP tunneling link: tuwien.auto.calimero.KNXTimeoutException: timeout connecting to control endpoint /192.168.10.13:3671`

**Comment by bmalinowsky** [comment]
The log literally tells you that the link tries to 
`establish connection from 192.168.62.198:59189 to 192.168.10.13:3671 (udp)`
Your local address (first address in log entry) should quite likely be something like `192.168.10.x` (note the replacement of 62 with 10).

**Comment by AlexMun86** [comment]
Oh, I see, maybe that's because I've used my phone to share internet with my PC. I will try this with a PC with static IP 192.186.10.xx.

**Comment by bmalinowsky** [comment]
All of the examples for IP communication have an option in the link creation wether to use NAT (network address translation) or not. If you use a phone you probably have to set that option `true` as networks over phone are usually NATted networks.

**Comment by AlexMun86** [comment]
Hi, thank you for the answer. I got it to work now. But this code just connect and disconnect right away. How can I keep it connected?

**Comment by bmalinowsky** [comment]
Take a look at the group monitor introduction, specifically line 65 [here](https://github.com/calimero-project/introduction/blob/82a452ccb2ed7caa8365e74456fe46afcdf6aad1/src/main/java/GroupMonitor.java#L65). It's a simple loop which only exits if the link got closed.

**Comment by AlexMun86** [comment]
Thank you, I will check that out. One more thing, I am doing this in Android Studio and wondering if it is possible to use native Button to for example turn off and on the lights? I am new to this java coding🙄

**Comment by bmalinowsky** [comment]
Re Button: I haven't used graphical stuff in android for years, so I don't know.
