### ISSUE TITLE
 How to read a device and read and write values

### ISSUE THREAD

**Issue by dufu-byte** [calimero-project/introduction#9]
Help MI

**Comment by calimero-project** [comment]
You probably want to try this example:
https://github.com/calimero-project/introduction/blob/master/src/main/java/ProcessCommunication.java

**Comment by myliwenbo** [comment]
![image](https://github.com/calimero-project/introduction/assets/29202248/15743499-ff40-4725-8501-4fd05cfb260b)

Excuse me, is TCP/IP written the same way, always time-out, not sure what the problem is

**Comment by myliwenbo** [comment]
![1691836782527](https://github.com/calimero-project/introduction/assets/29202248/02afe442-54d3-4a19-b048-a99340a1901e)

**Comment by dufu-byte** [comment]
GroupMonitor can be used to listen to data. But using https://github.com/calimero-project/introduction/blob/master/src/main/java/ProcessCommunication.java timeout

**Comment by calimero-project** [comment]
ProcessCommunication reads the datapoint `1/0/2`; someone has to respond, otherwise there will be a timeout.

**Comment by dufu-byte** [comment]
There is a question why it is possible to monitor when monitoring, and take the initiative to get it but not get it

**Comment by dufu-byte** [comment]
![image](https://github.com/calimero-project/introduction/assets/29202248/ff88caaf-c402-4b73-b54c-8f7df120171e)

Is there a way to add 3 remote IP addresses at the same time

**Comment by calimero-project** [comment]
You have to create a new tunneling link for each remote address.
